services:
  mc-1: #サービス名
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1" #Minecraftバージョン
    volumes:
      - ./data/mc-1:/data #/data/(サービス名)にデータを保存
  mc-2:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25570:25565" #mc-1と被らないよう25570ポートに変更
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
    volumes:
      - ./data/mc-2:/data